environment:
  matrix:
    - PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python37-x64"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python35-x64"

install:
  - "%PYTHON%\\python.exe -m pip install -e ."

build: off

test_script:
    - "%PYTHON%\\python.exe -m pytest -v"
    - "%PYTHON%\\python.exe -m pycon verify"
    - "%PYTHON%\\python.exe -m tutorial_runner version"
    - "%PYTHON%\\python.exe -m tutorial_runner init"
    - "%PYTHON%\\python.exe -m tutorial_runner lesson"
    - "%PYTHON%\\python.exe -m tutorial_runner solve --yes"
    - "%PYTHON%\\python.exe -m tutorial_runner check"

#after_test:
    # None

#artifacts:
    # None

#on_success:
    # None
